<h2>Now I get it...</h2>
<p></p>
<p>You have the following code:</p>
<pre><code class="language-kotlin">fun main() {
    try {
        println(42 / 0)
    } catch (e: NumberFormatException) {
        println("Incorrect format!")
    } catch (e: Exception) {
        println("I got you now!")
    } catch (e: ArithmeticException) {
        println("Division by zero!")
    }
}</code></pre>
<p>What exception will be caught?</p>
